elasticsearch:
    image: elasticsearch
    ports:
        - "9200:9200"
    volumes: 
        - ./elasticsearch:/usr/share/elasticsearch/config
kibana:
    image: kibana
    ports:
        - "5601:5601"
    links:
        - elasticsearch
